### ISSUE TITLE
Skipping Content validation due to: validationObjective (C-CDA_IG_Plus_Vocab) 

### ISSUE THREAD

**Issue by codemayankpant** [siteadmin/reference-ccda-validator#16]
I followed the instruction given at https://github.com/siteadmin/reference-ccda-validator/blob/master/README.md and configured and deployed the .war as per instructions.

I tried to validate the xml with http://localhost:9998/referenceccdaservice/static/validationui.html
1. I m selecting system as a "Sender"
2. C-CDA IG conformance criteria as "C-CDA_IG_Plus_Vocab"
3. Scenario file as "Readme.text"
4. Upload file as NT_CCDS_Sample4_r21_v3.xml

But failing to get any of the "ONC 2015 S&CC Vocabulary Validation Conformance Error". I m getting  "C-CDA MDHT Conformance Errors" as expected.

Also I checked the log files and  it is skipping the "C-CDA_IG_Plus_Vocab as validation objective".....

01:10:35,607 INFO  [VocabularyLoadRunner:101] Value Sets loaded...
01:10:35,608 INFO  [VocabularyLoadRunner:105] !!!!*********** VOCABULARY DATABASE HAS FINISHED LOADING - SERVER WILL CONTINUE AND SHOULD BE DONE SHORTLY. ***********!!!!
01:10:35,668 INFO  [DefaultLifecycleProcessor:341] Starting beans in phase 2147483647
01:10:35,668 INFO  [DocumentationPluginsBootstrapper:120] Context refreshed
01:10:35,685 INFO  [DocumentationPluginsBootstrapper:123] Found 1 custom documentation plugin(s)
01:10:35,695 INFO  [ApiListingReferenceScanner:44] Scanning for api listing references
01:10:35,864 INFO  [ContextLoader:347] Root WebApplicationContext: initialization completed in 4600 ms
01:10:35,871 INFO  [DispatcherServlet:489] FrameworkServlet 'dispatcher': initialization started
01:10:35,874 INFO  [AnnotationConfigWebApplicationContext:578] Refreshing WebApplicationContext for namespace 'dispatcher-servlet': startup date [Fri Jul 28 01:10:35 IST 2017]; parent: Root WebApplicationContext
01:10:35,892 INFO  [DispatcherServlet:508] FrameworkServlet 'dispatcher': initialization completed in 20 ms
01:12:19,520 INFO  [ReferenceCCDAValidationService:164] Attempting MDHT validation...
01:12:19,559 INFO  [ReferenceCCDAValidator:82] Mapped mdhtValidationObjective: NonSpecificCCDAR2
01:12:20,661 INFO  [ReferenceCCDAValidator:90] Loading mdhtValidationObjective: NonSpecificCCDAR2 mapped from valdationObjective: C-CDA_IG_Plus_Vocab
01:12:23,944 INFO  [ReferenceCCDAValidator:64] Processing and returning MDHT validation results
01:12:23,955 INFO  [ReferenceCCDAValidationService:104] Adding MDHT results
01:12:23,955 INFO  [ReferenceCCDAValidationService:169] Attempting Vocabulary validation...
01:12:24,876 INFO  [ReferenceCCDAValidationService:113] Adding Vocabulary results
01:12:24,877 INFO  [ReferenceCCDAValidationService:124] Skipping Content validation due to: validationObjective (C-CDA_IG_Plus_Vocab) is not relevant or valid for Content validation
--------------------------------------------------------------------------------------------------
Attached is the VSAC file for your reference.
[1.3.6.1.4.1.12009.10.2.5.xlsx](https://github.com/siteadmin/reference-ccda-validator/files/1182929/1.3.6.1.4.1.12009.10.2.5.xlsx)

Your help is appreciated !

**Comment by meimeipang** [comment]
We have the same problem. Could you please provide guidance at your earliest convenience? Thank you in advance for your help.

**Comment by drbgfc** [comment]
Content validation is for negative testing and is not the same as Vocabulary validation. C-CDA_IG_Plus_Vocab is supposed to skip Content Validation. So the issue title, "Skipping Content validation due to: validationObjective (C-CDA_IG_Plus_Vocab)" is what is supposed to happen as it is not related to skipping "ONC 2015 S&CC Vocabulary Validation Conformance." What has been skipped is the 'Reference' results. As such we should probably update the issue title eventually or start a new one.
However, if you are only getting MDHT results and you're sure that the file should return Vocabulary Validator results as well, then there is an issue somewhere. The log states "01:12:24,876 INFO [ReferenceCCDAValidationService:113] Adding Vocabulary results" though so either the results should be there or be there but empty.
1. In an effort to get the ball rolling on a resolition - do you only not see vocabulary results with the file, NT_CCDS_Sample4_r21_v3.xml or is it all files with the same setup?
2. Can you provide the returned JSON?
3. Does this happen for you in SITE as well?

Note: I will be slow to respond to this as I have a lot on my plate at the moment. Thank you for your patience.
-Dan

**Comment by codemayankpant** [comment]
Hi,
Do we have the latest release that was suppose to be available yesterday ? 
Issues was regarding the loading of VSAC files.
Thanks.

**Comment by drbgfc** [comment]
The release was pushed to today instead. Sorry for any confusion. You should see it later today.
