### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jxfish2** [siteadmin/reference-ccda-validator#29]
I am just going to ask my questions, all at once, in this thread.

From the following URL, I installed Tomcat, with its required Java.  I created all directory structures, and configured all files in accordance with the README.md.  There were no errors during any of the installation proceedings.  I staged only the xlsx files supplied via your instructions.  I did not stage any other code sets or value sets, aside from those provided on your github site.

     https://github.com/siteadmin/reference-ccda-validator

     When I attempted to start Tomcat, there were no errors or issues when starting Tomcat.

     However, when I attempted to access the URL, nothing came up.

     In troubleshooting, I found numerous Java create errors in the log files.

In response to the Java errors that I posted in another thread, you told me to take a look at the following URLs:

     https://github.com/siteadmin/code-validator-api/tree/master/codevalidator-api/docs

     If I look inside of the directory "ValueSetsHandCreatedbySITE", I see duplicate files, each with an "xls" and "xlsx" suffix.

     In one document posted on your site, it says to use only "xls" files.  But, in another document, it says to use "xlsx" files, and you provide both versions on your GitHub site.

     Which is correct?

     When I look at the download URL's, almost every file has both a "RAW" and a "BLOB" version, and even though the names are EXACTLY the same, they have completely different file sizes.

     In theory, there could be 4 completely different valueset files for each file name!

          XLS - RAW
          XLS - BLOB
          XLSX - RAW
          XLSX - BLOB

     Which one(s) should I use, or download to the valueset_repository?

     What is the difference between the "BLOB" and "RAW" versions?

     Finally, as these files all end in an XLS or XLSX, I must assume that the valuesets are nothing more than spreadsheet files.

     Is this correct, or does the XLS / XLSX extension have a different meaning / purpose here?

     Are we simply placing spreadsheet files in this valueset_repository?

**Comment by drbgfc** [comment]
-Can you hit these URLs in your browser (I'm not sure what port you are on but it should be something like this)?
--http://localhost:8080/referenceccdaservice/swagger-ui.html
--http://localhost:8080/referenceccdaservice/swagger-ui.html#!/reference-ccda-validation-controller/doValidationUsingPOST

-Have you tried hitting the endpoints directly in something like postman (and sending form data as per API)?
--http://localhost:8080/referenceccdaservice/
Note: visiting the above URL in a browser woudn't work since GET is not supported. This is intentional. The site-ui is a separate project and this instance is intended to be used with one's own UI, an endpoint call, or swagger above. Another option is...
---http://localhost:8080/referenceccdaservice/ui
Note: There is not support on above, it is a debug tool. We can't guarantee anything about it.

-Have you resolved your " Error creating bean with name " issues?

-For the value sets, one must use '.xlsx' with the most recent versions of the WAR vs the older '.xls' format. We used to use '.xls' but upgraded since then and still supply them in case someone wants to use an older version of the WAR. At this point it would probably make sense to remove them though.

-Yes, these are simply spreadsheet files. This allows one to create and add their own value sets.

" When I look at the download URL's, almost every file has both a "RAW" and a "BLOB" version, and even though the names are EXACTLY the same, they have completely different file sizes."
-What download URLs are you referring to - as in, on the github webapp? If not, which file are they located in on the repo? Or are you referring to VSAC? Something else? The difference between raw and blob is not specific to this project or github. We don't provide blob vs raw that I know of - that's a user choice based on a github option. Maybe I am mistaken though, if so, we should not be. If you clone (https://github.com/siteadmin/code-validator-api.git) or download the entire repo from this page https://github.com/siteadmin/code-validator-api it will be raw and there is no other option. This is what should be done and is the standard. If you download each file individually you may get a choice, but there is no reason you should want a binary version: blob = binary large object (sort of, it's a backronym). 

-If you need further help
--Can you post the log files here?
---What you see on startup and the log for that date in tomcat/logs/ e.g. referenceccdaservice.2018-08-XX.log
--It would be good to see these as well:
---file structure of value set repo and code repo
---referenceccdaservice.xml (located tomcat/conf/Catalina/localhost)
---Do you have your ccdaReferenceValidatorConfig.xml located in the path configured in referenceccdaservice.xml
