### ISSUE TITLE
Result Observation (V3) Missing Error

### ISSUE THREAD

**Issue by desai827** [siteadmin/reference-ccda-validator#49]
There should be an error thrown for the Result Observation (V3) value (CONF: 1198-7143) when **xsi:type="PQ"** and no _unit_ is included.

The SITE validator throws the error but the refererence-ccda-validator does not.

**Comment by drbgfc** [comment]
The SITE validator is a deployment of the reference-ccda-validator. Are you using the latest version of the ref val? https://github.com/siteadmin/reference-ccda-validator/releases/tag/1.0.37 and is it using the latest version of the code val https://github.com/siteadmin/code-validator-api/releases/tag/1.0.18 ? It's possible we made a mistake but to determine that would need to know more specifics. Are you deploying via the war from the release? Are you building locally? Thanks, Dan.

**Comment by desai827** [comment]
We've deployed using the WAR from the release and are not building locally. Would the ref val and code val items you mentioned apply since we're not building locally?

**Comment by drbgfc** [comment]
If downloaded and deployed this war: https://github.com/siteadmin/reference-ccda-validator/releases/download/1.0.37/referenceccdaservice.war
- Then the latest code val should be included and you shouldn't need to worry about any other versions, correct. But, since you are not seeing the latest version in testing, when I get time, I will test it to make sure the correct war was uploaded to the release (for the error you are seeing to have happened, the war would have needed to have been built on accident with a prior code val dependency). In the meantime, you might want to try this as sometimes tomcat will cache old data causing an issue:
-shutdown tomcat
-wait a bit or check log to know it's fully stopped
-go to your web apps directory
-delete the referenceccdaservice folder recursively (if shell run rm -rf referenceccdaservice )
-start tomcat

**Comment by desai827** [comment]
I'll wait for an update.

We did try the approach you suggested prior to posting the issue and confirmed it persisted even afterward.

**Comment by drbgfc** [comment]
Thanks for the info - can you try this [war](https://github.com/siteadmin/reference-ccda-validator/releases/download/1.0.37/referenceccdaservice_v2.war)  and let me know how it goes? Please remove '_v2' from name before deploying.

**Comment by desai827** [comment]
Hey Dan,

We did the following:

1. Shutdown the server.
2. Removed the old referenceccdaservice folder and WAR file.
3. Copied the new file onto the server and renamed it.
4. Started the server.

I'm still seeing that the error isn't showing up.

**Comment by drbgfc** [comment]
The war given was copied from the production SITE/ETT production server. So the issue is not the war or the release provided war then as you are using the same one as SITE. We will have to determine what is different about you environment - My guess is that your ccdaReferenceValidatorConfig.xml is out of date

**Comment by desai827** [comment]
I thought that and replaced the ccdaReferenceValidatorConfig.xml with the one here: https://github.com/siteadmin/reference-ccda-validator/blob/master/configuration/ccdaReferenceValidatorConfig.xml and then restarted tomcat

**Comment by desai827** [comment]
Alright, not sure what but I give it some more time and it appears to be working now after replacing the config file.

Thanks for the help!

**Comment by drbgfc** [comment]
Ok great - glad the latest config helped - thanks, Dan
