### ISSUE TITLE
Validator Appears to Crash/Abort

### ISSUE THREAD

**Issue by desai827** [siteadmin/reference-ccda-validator#52]
I've attached three files below:

- [Temp 1](https://github.com/siteadmin/reference-ccda-validator/files/2822968/temp1.txt) is the **original** file that leads to the validator crashing (on the SITE website it shows the following error.
![error](https://user-images.githubusercontent.com/7298157/52143475-8f3a7b80-2629-11e9-8361-792d3967782b.png)
- [Temp 2](https://github.com/siteadmin/reference-ccda-validator/files/2822969/temp2.txt) is the Temp 1 file with only the _Encounter_ section. It's by far the largest section.
- [Temp 3](https://github.com/siteadmin/reference-ccda-validator/files/2822970/temp3.txt) is the Temp 1 file without the _Encounter_ section.

Hoping you can take a look and figure out why it's crashing and/or displaying the error. I posted on the Google group with little success.

**Comment by desai827** [comment]
[Temp 4](https://github.com/siteadmin/reference-ccda-validator/files/2833653/Temp4.txt) is the Temp 1 file using the _Minify_ option on [this](https://codebeautify.org/xmlviewer) website; It essentially removes all extraneous line break.

This version of the file works with the SITE validator.

**Comment by harmonf** [comment]
Any update here?  I haven't seen this acknowledged or assigned so I'm curious if they can confirm the defect and possible solution date.

**Comment by drbgfc** [comment]
Apologies for the delay - I will assign to myself but don't think I can look into it until later this week.

**Comment by drbgfc** [comment]
I have tested both files in a local validator without issue. So it is not an issue with the API/ref val software itself.

I also tested at https://sitenv.org/sandbox-ccda/ccda-validator without issue. Although it does take a long time as it is a large file.

***However, my test at https://ttpedge.sitenv.org/ttp/#/validators/ccdar2 failed, instantly. I'm guessing this is where you tested. Due to the instant fail it seems likely, as you have also suggested, that there is some sort of size-limitation being imposed by the software ifself. Or perhaps it is related to some extra parsing ETT does. In this case, due to the above testing, that software requirement (or bug) would likely only be existent in the ETT front end code.

So this is confirmed as a bug, but techincally it is not a bug in the software that this repo contains. Therefore, I have closed this issue and opened a new one for it at that repo:
https://github.com/siteadmin/ett/issues/36

We will look into a resolution soon but if you need to test these files right away there are other reliable ways with equivalent results (SITE internal prod and a local instantiation).

Thanks for bringing this to our attention.

-Dan

**Comment by desai827** [comment]
Dan,

When you say you tested both files in a local validator without issue, were you accessing the validator locally from an intranet or the internet? I ask because I'm still having issues with that file in our local validator.

Thanks.

**Comment by drbgfc** [comment]
Interesting. I was running a local tomcat server on my personal windows PC.  Can you provide the log file for your local validator? The one that starts with reference and ends with the date you encountered the issue. That should help determined at least why it failed in your case. Also, are you running the latest war from February?

**Comment by harmonf** [comment]
Krishna,

Do you know if we are still seeing this locally?

Fred Harmon  |  Senior Director, Product Development, R&D Intergy
Greenway Health  |  13545 Progress Blvd., Alachua, FL 32615
(386) 418-7325 office  |  (352) 262-4656 mobile  |  GreenwayHealth.com<http://www.greenwayhealth.com/>

**Comment by desai827** [comment]
Dan - it doesn't appear to be an issue locally and we think it may have to do with our load-balance configuration.

**Comment by drbgfc** [comment]
Ok thanks a lot for the update
