### ISSUE TITLE
Configuration for result types validated against?

### ISSUE THREAD

**Issue by harmonf** [siteadmin/reference-ccda-validator#61]
I looked at the code but couldn't see a way.  Could this be easily enhanced to support the configuration of letting the user decide which types [Error, Warning, Info] are processed and eventually returned.

We have huge performance issues and delays with documents larger than 2 of 3 MB (which is very common for patient's that have been with a practice 10+ years).  It we could limit the engine from even running "Info" types, we could configure our system to exclude these when running in production and enable them during dev and QA potentially.  

Would something like this provide value to others, how quickly could such a change be done?  Are you open to other's making the change and committing?

**Comment by drbgfc** [comment]
Understood. On the technical side it is defintely possible with our codebase directly with the exception of the MDHT results. That could be updated in the MDHT API though. However, those results are blazingly fast so that's irrelevant. The major bottleneck is the vocabulary validation. And 2nd, would be content validation. I am not opposed at all to implementing it. I don't think it would be all that difficult -just requires lots of testing to make sure there are no side effects. I can ask the ONC what they think. I am also not opposed to any external contributions, in any case. I would just have to review first.
On another note, I am defintely looking into improving performance in general, it just hasn't been able to be a priority to implement yet. I'll add this comment to that 'check box' too.

**Comment by drbgfc** [comment]
Are you doing offline validation - it might be easier, from a policy standpoint - to only make it available offline.

**Comment by harmonf** [comment]
What do you mean by offline validation?  We are hosting load balanced instances of the validator such that all of our systems can run against it and attempt to guarantee decent performance.  

I appreciate your timely responses Dan.

**Comment by drbgfc** [comment]
What I meant was deployling and using the application yourself via the API, or potentially the built in angular1 'static' UI. Which from the sounds of it, you are doing one of this things since you are deploying multiple instances and using those vs accessing SITE (https://sitenv.org/sandbox-ccda/ccda-validator) or ETT (https://ttpedge.sitenv.org/ttp/#/validators/ccdar2) or using the public prod API directly (https://ttpds.sitenv.org:8443/referenceccdaservice/).

**Comment by harmonf** [comment]
Gotcha.  Yes, we are deploying ourselves and using the API.  We had considered just making the change ourself, however we don't want to fork from the master as we need to stay updated.  My hope was that this would be a useful change for others as well.

Just as an FYI, I had also mentioned this on the edge test tools google group and got a response from Dragon.  Didn't want to end up seeing double work, wasn't sure if you guys worked together.

https://groups.google.com/forum/#!topic/edge-test-tool/fTrLOl5UWgc

**Comment by drbgfc** [comment]
Yeah in that case I don't see any reason why there would be any objection to it. I think from the online UI standpoint (SITE and ETT) it is a bit tougher because we want to convey that validation is being done which covers all possible bases. And, we don't want any confusion where someone suspects something may have passed that actually didn't (even if it's limited by their own selection, so more likely a 3rd party). But from an offline perspective where folks are implementing the application on their own servers - I should think that we could provide whatever functionality such users may find useful without much negotiation. Anyway, after addressing a few other issues this month, I will look into the complexities of this. 
Oh and thanks for the reference to ETT, I had seen that today and yes Dragon and myself work together on SITE.
Thanks, Dan

**Comment by drbgfc** [comment]
This is available in the latest release (with the exception of content results, but should be coming soon) - let me know how it works out for you. Thanks, Dan.

https://github.com/siteadmin/reference-ccda-validator/releases/tag/1.0.41

**Comment by harmonf** [comment]
Great news Dan.  Thanks so much.  We’ll let you know how it works.


Fred Harmon  |  Senior Director, Product Development, R&D Intergy
Greenway Health  |  13545 Progress Blvd., Alachua, FL 32615
(386) 418-7325 office  |  (352) 262-4656 mobile  |  GreenwayHealth.com<http://www.greenwayhealth.com/>

**Comment by harmonf** [comment]
Can you explain what you mean by filtering of content results (coming soon) versus what you’ve just done?  I want to make sure I share with the teams appropriately.


Fred Harmon  |  Senior Director, Product Development, R&D Intergy
Greenway Health  |  13545 Progress Blvd., Alachua, FL 32615
(386) 418-7325 office  |  (352) 262-4656 mobile  |  GreenwayHealth.com<http://www.greenwayhealth.com/>

From: Harmon, Fred
Sent: Tuesday, June 25, 2019 12:46 PM
To: 'siteadmin/reference-ccda-validator' <reply@reply.github.com>; siteadmin/reference-ccda-validator <reference-ccda-validator@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [siteadmin/reference-ccda-validator] Configuration for result types validated against? (#61)

Great news Dan.  Thanks so much.  We’ll let you know how it works.


Fred Harmon  |  Senior Director, Product Development, R&D Intergy
Greenway Health  |  13545 Progress Blvd., Alachua, FL 32615
(386) 418-7325 office  |  (352) 262-4656 mobile  |  GreenwayHealth.com<http://www.greenwayhealth.com/>

**Comment by drbgfc** [comment]
Conformance results and Vocabulary results will adhere to the severity selected and up (more severe if available).
Content validation  (reference results, the 3rd column, the ones you compare with a pdf) will process and return all result types regardless. This is not what I would prefer but was simply limited by time to look into and update that type. Next release should filter those results as well.

**Comment by drbgfc** [comment]
Conformance results and Vocabulary results will adhere to the severity selected and up (more severe if available).
Content validation  (reference results, the 3rd column, the ones you compare with a pdf) will process and return all result types regardless. This is not what I would prefer but was simply limited by time to look into and update that last, 3rd, type. Next release should filter (before processing) those results as well.

**Comment by harmonf** [comment]
Makes sense.  Thanks for the clarification.


Fred Harmon  |  Senior Director, Product Development, R&D Intergy
Greenway Health  |  13545 Progress Blvd., Alachua, FL 32615
(386) 418-7325 office  |  (352) 262-4656 mobile  |  GreenwayHealth.com<http://www.greenwayhealth.com/>

**Comment by drbgfc** [comment]
FYI: The implementation for Content Validation (Ref Val results) limiting in addition to the already existing limitations for MDHT and Vocab will be available in the July release. The work is done now. Also, the SITE UI , https://sitenv.org/sandbox-ccda/ccda-validator, will support the severityLevel selection as well.
Unfortunately, I don't expect this to make a significant difference in performance. This is because Content Validation (if you even use it) doesn't produce any info messages ever. And, has quite a limited set of possible warnings. Nevertheless, those limited warnings won't be processed if Errors only is selected. The UI also includes a visual cue if there are actually zero issues of a certain type vs being limited to 0.

Thanks, Dan

**Comment by harmonf** [comment]
Thanks for the update.  We’ll likely just stick to the original changes you made in this case.


Fred Harmon  |  Senior Director, Product Development, R&D Intergy
Greenway Health  |  13545 Progress Blvd., Alachua, FL 32615
(386) 418-7325 office  |  (352) 262-4656 mobile  |  GreenwayHealth.com<http://www.greenwayhealth.com/>
